// Generated by CoffeeScript 1.4.0
(function() {
  var board, boards, camera, clock, controls, floor, foo, geometry, hud, hudCamera, hudScene, image, light, material, render, renderImage, renderer, scene, t, texture;

  t = THREE;

  $("body").click(function() {
    var element;
    element = $("body")[0];
    element.requestPointerLock = element.requestPointerLock || element.mozRequestPointerLock || element.webkitRequestPointerLock;
    return element.requestPointerLock();
  });

  renderImage = function(w, h, f) {
    var canvas, ctx, image;
    canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    ctx = canvas.getContext('2d');
    f(ctx);
    image = new Image();
    ctx.save();
    image.src = canvas.toDataURL();
    return image;
  };

  image = renderImage(500, 500, function(ctx) {
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(0, 0, 500, 500);
    ctx.fillStyle = "#FF0000";
    return ctx.fillRect(50, 50, 100, 100);
  });

  scene = new t.Scene();

  hudScene = new t.Scene();

  camera = new t.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);

  hudCamera = new t.OrthographicCamera(window.innerWidth / -2, window.innerWidth / 2, window.innerHeight / 2, window.innerHeight / -2, 1, 1000);

  hudScene.add(hudCamera);

  renderer = new t.WebGLRenderer();

  renderer.setSize(window.innerWidth, window.innerHeight);

  document.body.appendChild(renderer.domElement);

  light = new t.DirectionalLight(0xFFFFFF, 3);

  light.position.set(0.0, 20, 4);

  light.rotateOnAxis(new t.Vector3(1, 0, 0), -Math.PI * 0.15);

  scene.add(light);

  light = new t.AmbientLight(0x202020);

  scene.add(light);

  geometry = new t.BoxGeometry(13, 8, 0.1);

  texture = new t.Texture(image);

  texture.needsUpdate = true;

  material = new t.MeshLambertMaterial({
    map: texture
  });

  board = new t.Mesh(geometry, material);

  board.position.y = 12;

  board.position.z = -10;

  scene.add(board);

  boards = [board];

  material = new t.MeshLambertMaterial({
    map: t.ImageUtils.loadTexture("doge.jpeg")
  });

  floor = new t.Mesh(new t.PlaneGeometry(100, 100), material);

  floor.rotateOnAxis(new t.Vector3(1, 0, 0), -Math.PI / 2.0);

  floor.position.x = 0;

  floor.position.y = 0;

  floor.position.z = 0;

  scene.add(floor);

  clock = new t.Clock();

  controls = new t.PointerLockControls(camera);

  controls.enabled = true;

  scene.add(controls.getObject());

  material = new t.MeshBasicMaterial({
    color: "#00FF00"
  });

  hud = new t.Mesh(new t.PlaneGeometry(5, 5), material);

  hud.position.z = -10;

  hudScene.add(hud);

  hudScene.add(hudCamera);

  foo = 0;

  render = function() {
    var delta, isects, projector, ray;
    delta = clock.getDelta();
    controls.update(delta);
    projector = new t.Projector();
    ray = projector.pickingRay(new t.Vector3(0.0, 0.0, 0.0), camera);
    isects = ray.intersectObjects(boards, false);
    requestAnimationFrame(render);
    renderer.autoClear = true;
    renderer.render(scene, camera);
    if (isects.length > 0) {
      renderer.autoClear = false;
      return renderer.render(hudScene, hudCamera);
    }
  };

  render();

}).call(this);
