// Generated by CoffeeScript 1.4.0
(function() {
  var Room, t;

  t = THREE;

  Room = (function() {

    function Room(scene) {
      var material;
      this.light = new t.AmbientLight(0x606060);
      material = new t.MeshLambertMaterial({
        map: t.ImageUtils.loadTexture("doge.jpeg")
      });
      this.floor = new t.Mesh(new t.PlaneGeometry(100, 100), material);
      this.floor.rotateOnAxis(new t.Vector3(1, 0, 0), -Math.PI / 2.0);
    }

    Room.prototype.addToScene = function(scene) {
      scene.add(this.light);
      return scene.add(this.floor);
    };

    return Room;

  })();

  window.Room = Room;

}).call(this);
